services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./.local/.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_NAME:-pro-figure}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGUSER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./.local/.redis_data:/data
    ports:
      - "26379:6379"
