services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./.local/.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "redditrot"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "25432:5432"

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_USER: "redis"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./.local/.redis_data:/data
    ports:
      - "26379:6379"
