services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./.local/.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "25432:5432"

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./.local/.redis_data:/data
    ports:
      - "26379:6379"
